name: Starting test
run-name: ${{ github.actor }} is testing out GitHub Actions

on:
  workflow_dispatch:

  push:
    branches:
      - develop

env:
  PUBLIC_KEY: ${{ secrets.PUBLIC_KEY }}
  DB_HOST: ${{ vars.DB_HOST }}
  DB_USER: ${{ vars.DB_USER }}
  DB_PASS: ${{ vars.DB_PASS }}
  DB_NAME: ${{ vars.DB_NAME }}
  DB_STRICT_QUERY: ${{ vars.DB_STRICT_QUERY }}

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.x]

    steps:
      - name: Checking out
        uses: actions/checkout@v2

      - name: Using NODE.JS verion ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}

      - run: npm ci
      - run: npm run test
